# Generated by Django 5.2.2 on 2025-06-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_cliente_profesional_tratamiento_delete_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
            preserve_default=False,
        ),
    ]
