# Generated by Django 5.2.2 on 2025-07-11 03:24

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_consulta_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tratamientos/'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
